import com.perfm.finddoctorapp.model.Doctor
import com.perfm.finddoctorapp.model.Response

global com.perfm.finddoctorapp.model.Response responseResult

dialect  "mvel"

rule "doctor_details_validation"
    when
        Doctor(id == null || firstName == null || lastName == null || professionalStatement == null
                || id.isEmpty() || firstName.isEmpty() || lastName.isEmpty() || professionalStatement.isEmpty())
    then
        responseResult.setCode(2000);
        responseResult.setMessage("Doctor Id, firstName, lastName, professionalStatement are required values");

end


rule "specialization_details_validation"
    when
        Doctor(specialization.id == null || specialization.specializationName == null
                || specialization.id.isEmpty() || specialization.specializationName.isEmpty())
    then
        responseResult.setCode(2001);
        responseResult.setMessage("specialization.id , specializationName are required values");
end


rule "doctor_qualification_details_validation"
    when
        Doctor(qualification.id == null || qualification.qualificationName == null || qualification.institutionName == null || qualification.qualificationName == null
        || qualification.id.isEmpty() || qualification.qualificationName.isEmpty() || qualification.institutionName.isEmpty()
                                                              || qualification.qualificationName.isEmpty())
    then
        responseResult.setCode(2002);
        responseResult.setMessage("qualification.id, qualificationName, institutionName, qualificationName are required values");
end

rule "HospitalAffiliation_details_validation"
    when
        Doctor(hospitalAffiliation.id == null || hospitalAffiliation.id.isEmpty())
    then
        responseResult.setCode(2003);
        responseResult.setMessage("hospitalAffiliation.id is required value");
end

